### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by IanZmen** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#1]
Hola. ¿Van a subir las slides? si es así ¿Cuándo y donde?

**Comment by dfloreaa** [comment]
Hola Ian, perdona por la tardanza de la respuesta. Las issues están siendo subidas en Canvas, en la [página del curso](https://cursos.canvas.uc.cl/courses/60647)

Un saludo 😊✨
