### ISSUE TITLE
Demora correr test robot

### ISSUE THREAD

**Issue by jarvasquez** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#11]
Holaa! Esperando que se encuentren bien, vengo por un poco de ayuda.

Me pasa que en los testE6 y testE7 se me demora mucho correr la respuesta (40 mins y +90 mins, respectivamente). Esto me genera problemas al determinar si mi código está correcto por lo que me gustaría saber si es normal lo que estoy haciendo.

Adicionalmente, hice un análisis de sensibilidad y me di cuenta que la restricción que hace que el programa se demore tanto en correr es la línea donde tiene el siguiente comentario

`# No se pueden cruzar robots. No puede estar un robot y una caja sin levantar en la misma casilla.`

Supongo que es porque al editar estas líneas yo asigné una dirección y una energía diferente para cada instancia de onRobot que se escribe. Esto puede general muchas soluciones pudiendo retrasar el cálculo.

¿Como puedo reducir este tiempo de resolución?

**Comment by dfloreaa** [comment]
Hola, la solución de nuestra pauta toma 0.976 segundos en encontrar la solución al testE7, por lo que probablemente tu programa toma mucho tiempo en optimizar y encontrar una solución.

Si bien no puedo decir mucho más al respecto, revisando tu código si encuentro algunas recomendaciones para hacerte:
1. No utilizes `#maximize` o `#minimize` a menos de que sea estrictamente necesario, si tus reglas requieren a los robots utilizar toda su energía (o no más que ello), debería ser suficiente.
2. Ojo con el uso de las variables D y E, especialmente en la regla que dices que te da problemas, recuerda que los robots solo pueden moverse hacia adelante, así que se mantendrán iguales en dos instantes de tiempo en que se muevan adelante.
3. Recomiendo fuertemente resolver el problema con los predicados entregados, cada predicado que agregas hace crecer el programa **fuertemente**.
4. Lee e implementa directamente lo enunciado encima de una regla (al añadir D y E) por ejemplo, al definir la adyacencia de una caja, considera la energía disponible para el robot, o la regla de levantar cajas, en donde se comenta que el robot no gira, por lo que debe seguir mirando a la caja (el D es un valor conocido).
5. Revisa que reglas de tu código pueden ser simplificadas, algunas reglas pueden ser reescritas en menos líneas si las implementas distinto (por ejemplo, las rotaciones del robot al comienzo de tu código)

Si bien son un tanto "personalizados", creo que estos consejos pueden servirle a todo/a quien esté haciendo su tarea, espero que les sean útiles :) ✨
