### ISSUE TITLE
Test 5 DCCudoku

### ISSUE THREAD

**Issue by MelanyLillo** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#12]
Hola! existe la posibilidad de que el test 5 tenga algún error?, es que me funcionan todos los demás tests, pero en este específicamente no se libera una solución aunque saque todos los requisitos de mi código.

**Comment by dfloreaa** [comment]
Hola, aquí está la solución al test 5, mostrada en el visualizador y resuelto con la pauta:

![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/62019645/ed765ac2-3c10-4f83-952d-ea2d57ba1b28)

Por lo que no, no hay ningún error con el.

_PD: No sirve de nada hardcodear un problema ya que los test que les entregamos no son los utilizados para evaluar sus tareas._

**Comment by MelanyLillo** [comment]
Al final era porque en la línea 5 del test falta un n.
