### ISSUE TITLE
No se ve el robot en la visualización de DCCarrybot

### ISSUE THREAD

**Issue by dedmu5** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#14]
Básicamente lo que dice el título. Logro obtener el output.txt a partir de mi código. Modifiqué el código original para avanzar en mi tarea, pero cuando corro el visualizador no veo al robot.  Adjunto imágen:
![imagen](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/65060602/d1884dbf-deee-4f14-b478-74abd1dda37d)

**Comment by dfloreaa** [comment]
Hola, podrías compartir el contenido de tu archivo `output.txt`, por favor?

Saludos 😊

**Comment by dedmu5** [comment]
Solucionado. Perdón por no contestar antes. 
Por si le sirve a otra persona, este error me ocurrió porque algunos predicados tenían distinta aridad en el mismo código.
