### ISSUE TITLE
Pregunta sobre pregunta 2.2

### ISSUE THREAD

**Issue by nico-sv** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#16]
Hola, en teoría si los robots tienen cierta energía E y el test se resuelve en cierto bound T, si aumento la energía de cada robot en +X con el mismo bound T la solución debiera ser la misma a que si no hubiese modificado nada? Es decir, al finalizar el tiempo, los robots deberían tener energía X o no necesariamente?

**Comment by dfloreaa** [comment]
Hola, exacto. El `bound` especifica en cuantos pasos deberá ser resuelta la tarea, sobre o con la cantidad justa de energía.

**Comment by nico-sv** [comment]
Por ejemplo en mi implementación se resuelve bien el testE7, llegando todos los robots a la meta con energía 0, pero si voy al test y a los robots les cambio la energía de 10->15, 10->15, 7->12 y 6->11, para cada robot(0..3) respectivamente, llegan a la meta con 5, 6, 3 y 2 de energía respectivamente. Eso estaría bien o deberían llegar todos con 5 de energía (que vendría siendo la cantidad por la que aumenté la energía de cada robot)?

**Comment by dfloreaa** [comment]
@nico-sv Está bien, la idea eso sí es que los robots minimizen la energía utilizada en su ejecución. De todos modos, probaremos sus tareas otorgándoles el mínimo de energía necesario a cada robot, evaluando si logran una solución.
