### ISSUE TITLE
Dudas sobre acciones wait, uso de #minimize y compatibilidad entre soluciones 2.1 y 2.2.

### ISSUE THREAD

**Issue by vcrb18** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#17]
Hola, en este issue tengo tres preguntas:
- 1) Está bien que mis robots hagan el uso de la acción wait para que todos lleguen en el mismo T con energia 0 al final? Esta acción no utiliza energía por lo que no hay problemas de minimización.
- 2) Es necesario utilizar #minimize en la solución del 2.2, o se puede llegar a un resultado sin utilizarlo? Porque actualmente no lo he usado y logro correr todos los test cases.
- 3) Al tener la solución 2.2 implementada, debieran correr los tests de la solución 2.1? Cuando implementé 2.1 me funcionaban pero ahora con 2.2 no corren los tests del 2.1, me tira error. Tiene sentido esto o es algún error mio?

**Comment by dfloreaa** [comment]
Hola, respecto a tus preguntas:

1. Sí
2. No, la energía entregada en el archivo es la mínima necesaria, con tal de que resuelva el problema con esa cantidad está bien, en todo caso, sería ideal minimizar la energía sin importar el límite (no obligatorio).
3. Si, deberían correr todos siempre y cuando se defina la energía de los robots (asegúrate de que sea el caso).

Éxito con tu tarea ✨
