### ISSUE TITLE
Test 3 DCCudoku

### ISSUE THREAD

**Issue by rominaansaldo** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#18]
Hola! Tenía una preguntar acerca del test 3, las coordenadas asignadas a los bloques de ciertas figuras no son consistentes... en algunas figuras le atribuyen el número del siguiente bloque hacia la derecha y en otras lo empiezan a asignar primero hacia abajo. No se si se entiende muy bien, igual dejo un ejemplo abajo :)

% Figura 2
% 2 4
% 1 6
bloque(4,2,0,0,2).
bloque(5,2,1,0,1).
bloque(6,2,1,1,6).
bloque(7,2,0,1,4).

% Figura 5
% 5 1
% 4 3
bloque(15,5,0,0,5).
bloque(16,5,0,1,1).
bloque(17,5,1,0,4).
bloque(18,5,1,1,3).

En la figura 2 por ejemplo parten por el 2, luego el 1, luego el 6 y finalmente el 4 (osea bajan, para el lado y después suben). En cambio en la figura 5, que es la misma figura, asignan los bloques diferente, primero la primera linea y luego la segunda. En la tarea sale explícito que los bloques se asignan respetando las filas, es decir, primero la linea 1 hacia la derecha y luego linea 2 hacia la derecha. 

Esto me genera dificultades con lo que tengo en mi código, puedo cambiar el test 3 y respetar lo que sale en el enunciado? :)

Muchas gracias!

**Comment by dfloreaa** [comment]
Claro que si, siempre y cuando sean las mismas lineas, no hay problema :)
