### ISSUE TITLE
Mismo problema de la issue #10

### ISSUE THREAD

**Issue by Maryangelm27** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#19]
Hola! Yo estoy teniendo el mismo problema de la issue #10, estoy corriendo el código con la misma línea de comandos que mostró el compañero. Ya intenté cambiar el slash y no funcionó, también puse el print(content) en la línea 7 del parser.py pero el output.json sigue saliendo vacío a pesar de que en la terminal si sale una solución. Que puedo hacer?

**Comment by rominaansaldo** [comment]
A mi me pasaba que tenía que comentar el show que tenía en el código (con %), sino no me salía el archivo json. Quizás te sirva! :)

**Comment by dfloreaa** [comment]
Hola @Maryangelm27,

Podrías compartir el print de los contenidos de salida de tu programa de clingo? Quizás el problema está en que no estas haciendo los `show` correctos como comenta Romina.

Avisame que tal, un saludo ✨

**Comment by Maryangelm27** [comment]
Nose si entiendo bien lo que quieren decir con el "show" pero lo que me sale en la terminal es esto. Sale la solución pero abajo dice "Grid size not found in the content" y nose si sea eso lo que no deja que aparezca la solución al descargar el output.json

![Problema cudoku](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/141956715/3b720601-ddef-4cea-b16f-0f2c9f51b85f)

**Comment by OscarCampohermoso** [comment]
Parece que alguien en el grupo de Telegram enfrentó un problema similar. Es posible que el origen del problema se encuentre en el archivo "solucion.lp", ya que el mensaje de error "Grid size not found" se relaciona con Python. Mi teoría es que tanto "solucion.lp" como los tests podrían tener conflictos en ciertos predicados, lo que a su vez podría ocasionar que grid size no se defina correctamente.

**Comment by dfloreaa** [comment]
@Maryangelm27 se debe a que la salida de tu programa es solamente los predicados solución. Debes remover ese `show` y que clingo muestre todos los predicados para que funcione correctamente. Esto es debido a que para calcular el `gridSize` se necesita del predicado `grid(M, N)`.

Saludos
