### ISSUE TITLE
Gasto energetico al cambiar la direcccion DCCarryBot 2.2

### ISSUE THREAD

**Issue by roahoki** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#21]
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/89496233/b64917c3-0d62-4fa7-b316-aeb4f1f6ac7c)

Hola buenas! en esta parte del enunciado creo que hay una contradiccion a menos que lo esté entendiendo mal, debo considerar un gasto de energía cada vez que un robot gire en su propio eje o no? 🧑🏼‍🚀

**Comment by dfloreaa** [comment]
Si, la segunda parte hace referencia a no moverse en lo absoluto. Disculpas por el error que podria interpretarse.

Un saludo ✨
