### ISSUE TITLE
Problem ISSUE 10 - VISU DCCUDOKU

### ISSUE THREAD

**Issue by STageAmp** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#22]
<img width="602" alt="Capture d'écran 2023-09-07 050540" src="https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/116718498/e63b96de-fe50-4d3e-9592-dbf2bbe20700">

Mi problema es que, mientras que el file .json existe, nada se pasa cuando lo cargo en el visualizador, no sé si olvidé algo importante...

**Comment by dfloreaa** [comment]
Hola, podrías compartir tu archivo output3.json al correo del curso? iic2613@ing.puc.cl

De este modo puedo revisarlo y ver cual es el problema, ¿al abrir el archivo está vacío?

Un saludo:)

**Comment by STageAmp** [comment]
Lo envio, muchas gracias
