### ISSUE TITLE
PROBLEM ISSUE 2 json dccarrybot

### ISSUE THREAD

**Issue by STageAmp** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#23]
<img width="841" alt="image" src="https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/116718498/75deb8ff-0b4c-4f9e-819f-7ad7c92dc5f3">
Hola, 
Muchas gracis por su ayuda ^^
Aca, mi problema es que no puedo generar el file .json para los tests del DCCARRYBOT. 
Intenté con muchas maneras pero todo siempre me sale esta error con instruccion de este tipo " clingo tarea2_robot.lp tests/testD2.lp -c bound=14 | python process.py"

**Comment by dfloreaa** [comment]
Podrías correr la línea sin la parte de python, es decir

`clingo tarea2_robot.lp tests/testD2.lp -c bound=14`

Y compartir la salida de tu programa, por favor?

Un saludo

**Comment by STageAmp** [comment]
Hola, 
Muchas gracias por su respuesta ! 
Voila la salida preguntada : 
<img width="952" alt="image" src="https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/116718498/f5f9e157-a708-471c-a221-717fc96fb8be">

**Comment by dfloreaa** [comment]
@STageAmp recuerda que las variables en Clingo se deben escribir con MAYÚSCULAS, intenta cambiar todas las reglas para usar este tipo de letras en lugar de minúsculas (por ejemplo, `robotOn(R, X, Y, T, D, E)` en lugar de `robotOn(r, x, y, t, d, e)` y cuéntame cómo te va.

Saludos ✨

**Comment by STageAmp** [comment]
Hola, el problema es que cuando pongo todas las variables con mayusculas no esta posible tener compilacion : 
<img width="580" alt="image" src="https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/116718498/5fdf09dd-5cbe-4440-b1b3-2042e1ce9b66">

**Comment by dfloreaa** [comment]
Resuelto via correo, se debe al uso de variables a la izquierda de una regla sin definirlas al lado izquierdo
