### ISSUE TITLE
Error función max()

### ISSUE THREAD

**Issue by AgustinKA** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#24]
Hola!

He estado tratando de correr en la terminal el código de robots.lp:
"clingo FILENAME.lp tests/TESTNAME.lp -c bound=N | python3 process.py"

Al correrlo me tira dos errores que no logro entender:
1. robots.lp:107:25-39: info: atom does not occur in any rule head:
  obstacle(X,Y)

2. line 69, in <module>
    answer.range_x = max(map(lambda x: get_number(
ValueError: max() arg is an empty sequence

Más que no entender, no se si es error mío o no.
Me ayudan?

Gracias!

**Comment by dfloreaa** [comment]
Hola, el primer error ocurre en el `testD1.lp` debido a que ningún obstáculo es definido en este mapa, no debería haber problema con ello. Aunque puedes diseñar tu código para tener esto en cuenta (ver último comentario de la issue #2).

El segundo error hace referencia a que no se obtiene una solución para el programa (no es SATISFACIBLE como dice Clingo). Puedes ver la salida de tu programa ejecutando el test como
`clingo FILENAME.lp tests/TESTNAME.lp -c bound=N`

Es decir, sin la parte de Python.

Avísame si necesitas más ayuda, saludos! ✨
