### ISSUE TITLE
Tiempos de ejecución DCCudoku

### ISSUE THREAD

**Issue by raibd** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#25]
Hola, estoy ejecutando los tests de DCCudoku y todos menos el primero se demoran mucho. Lo que no me calza es que el primer test entrega la respuesta correcta, pero al correr el resto nunca terminan.

**Comment by dfloreaa** [comment]
Hola @raibd, te recomiendo fuertemente añadir reglas (o refrasear algunas) que limiten el espacio de trabajo de tu programa, especialmente en problemas como puzzles la calidad de tus reglas influye fuertemente en cómo Clingo encuentra la solución al problema.

En la issue #11 doy un par de tips para el otro ejercicio de la tarea, quizás algo pueden ayudarte, avísame si no :)

**Comment by raibd** [comment]
> 

La verdad no se me ocurre como cambiar mi código, ya que en total (sin contar los comentarios) son como 6 líneas.

**Comment by dfloreaa** [comment]
Hola, te recomiendo pensar en restricciones tales como "no puede haber un bloque posicionado más allá de los límites", "no se pueden superponer bloques", "un bloque solo aparece 1 vez", etc. Es decir, restricciones que limitan un poco el dominio sobre el que se buscan soluciones.

Un saludo ✨

**Comment by raibd** [comment]
Intenté agregar todas esas restricciones y aún así nunca termina la ejecución de los tests del 2 en adelante. No logro ver qué  esta mal.

**Comment by dfloreaa** [comment]
Te recomiendo subir tu código actualizado a tu repositorio, le echaré un ojo para ver si es algo aparente. En todo caso, recomiendo fuertemente ir removiendo reglas hasta llegar a la que genera la demora.

**Comment by raibd** [comment]
> Te recomiendo subir tu código actualizado a tu repositorio, le echaré un ojo para ver si es algo aparente. En todo caso, recomiendo fuertemente ir removiendo reglas hasta llegar a la que genera la demora.

Ok, lo acabo de subir.

**Comment by dfloreaa** [comment]
Revisando tu código aquí algunas sugerencias:
1. Ojo con tu regla de que un mismo bloque solo aparece una vez, similar para la de bloques que no pueden quedar en un mismo lugar (en tu caso, deben ser definidos en una sola línea)
2. Intuyo fuertemente que tu programa se demora por como modelaste la regla `Para bloques en la misma figura, la diferencia entre sus posiciones relativas es igual a la diferencia entre sus posiciones reales`
3. Recuerda que mientras más acotes el problema, más rápida debería ser la obtención de soluciones, busca otras reglas que aplican a las soluciones de este.
4. Si te está costando mucho esta parte, te recomiendo fuertemente comenzar con `DCCarrybots`, que ya incluye un ejercicio modelado

Lamentablemente no puedo brindarte más ayuda sin ponerte en una posición favorable respecto al resto de tus compañeros, un saludo

**Comment by raibd** [comment]
Ok, voy a revisar mi solución teniendo todo eso en cuenta. Gracias!

**Comment by bernirosas** [comment]
> Revisando tu código aquí algunas sugerencias:
> 
> 1. Ojo con tu regla de que un mismo bloque solo aparece una vez, similar para la de bloques que no pueden quedar en un mismo lugar (en tu caso, deben ser definidos en una sola línea)
> 2. Intuyo fuertemente que tu programa se demora por como modelaste la regla `Para bloques en la misma figura, la diferencia entre sus posiciones relativas es igual a la diferencia entre sus posiciones reales`
> 3. Recuerda que mientras más acotes el problema, más rápida debería ser la obtención de soluciones, busca otras reglas que aplican a las soluciones de este.
> 4. Si te está costando mucho esta parte, te recomiendo fuertemente comenzar con `DCCarrybots`, que ya incluye un ejercicio modelado
> 
> Lamentablemente no puedo brindarte más ayuda sin ponerte en una posición favorable respecto al resto de tus compañeros, un saludo

Hola Daniel! Me pasa algo parecido, ¿podrías revisar mi código?

**Comment by dfloreaa** [comment]
@bernirosas te recomiendo fuertemente que algunas restricciones las modeles mediante reglas que **restrinjan** al modelo. Por ejemplo, la forma en que modelas que filas tengan un mismo número (igual que para columnas), puede ser modelada mediante una regla sin _Head_ (ej, `:- sacar(X)`). De este modo el programa sabe que todo modelo no puede cumplir el predicado `sacar(X)` (obviamente definiendo de donde viene `X` también).

También te recomiendo fuertemente intentar añadir un par de predicados "redundantes" como los que entregué en esta y otras issues, eso ayuda (muchas veces, no siempre) a acotar el problema y encontrar soluciones más rápidamente.

Saludos

**Comment by bernirosas** [comment]
Hola! Tomé tus recomendaciones y bajé un poco el tiempo, hay algo más que pueda hacer, todavía se demora minuto y medio en el test 2 y ya al 3 se muere.
Muchísimas gracias.

El 09-09-2023, a las 15:25, Daniel Florea ***@***.***> escribió:



@bernirosas<https://github.com/bernirosas> te recomiendo fuertemente que algunas restricciones las modeles mediante reglas que restrinjan al modelo. Por ejemplo, la forma en que modelas que filas tengan un mismo número (igual que para columnas), puede ser modelada mediante una regla sin Head (ej, :- sacar(X)). De este modo el programa sabe que todo modelo no puede cumplir el predicado sacar(X) (obviamente definiendo de donde viene X también).

También te recomiendo fuertemente intentar añadir un par de predicados "redundantes" como los que entregué en esta y otras issues, eso ayuda (muchas veces, no siempre) a acotar el problema y encontrar soluciones más rápidamente.

Saludos

**Comment by dfloreaa** [comment]
@bernirosas te recomiendo intentar reescribir algunas de las reglas, puede ser que otra sintaxis sea más eficiente en la búsqueda de soluciones.

Saludos ✨
