### ISSUE TITLE
Duda sobre como definir variables constantes en reglas

### ISSUE THREAD

**Issue by dedmu5** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#26]
En algunas partes del código de DCCarrybot, cuando se le fija un valor constante a una variable utilizan dos métodos, tal como en el siguiente caso:
`boxAdjacentToRobot(B, R, 0) :- robotOn(R, X - 1, Y, 0, D), boxOn(B, X, Y, Z, 0), robot(R), box(B), Z = 0.`
Mi pregunta es cual es la diferencia entre:
1) reemplazar 0 en la posición de la variable Z 
2) Definir Z = 0 
Gracias de antemano.

**Comment by dfloreaa** [comment]
Hola, son esencialmente lo mismo, es como si en Python definieras (pero solo por una línea) que una cierta variable tiene un valor en lugar de reemplazar este valor directamente.

Saludos ✨
