### ISSUE TITLE
Test 1 DCCudoku

### ISSUE THREAD

**Issue by tamyhan** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#27]
Hola! En la figura 1 del test 1 según el comentario de como deberían estar ordenados los bloques (1 2 3), están al revés las X con las Y o no?
Para que se cumpla ese orden no debería ser así?
bloque(1,1,0,0,1).
bloque(2,1,1,0,2).
bloque(3,1,2,0,3).

![Captura de pantalla 2023-09-08 a la(s) 09 08 47](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/71773541/073e7d9e-a419-4c8f-a9b4-4da6c633dca3)

**Comment by dfloreaa** [comment]
Hola, te recomiendo revisar el final de la issue #9, en DCCudoku el eje X apunta hacia abajo y el eje Y hacia la derecha, mientras que el DCCarrybots, el eje X apunta hacia la derecha y el eje Y hacia abajo. Fue una descoordinación entre ambos equipos de la tarea, disculpas.

Un saludo y éxito con tu tarea ✨

**Comment by tamyhan** [comment]
Ahh perfecto, muchas gracias!
