### ISSUE TITLE
Pregunta sobre minimización de energia

### ISSUE THREAD

**Issue by v4rgas** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#3]
Hola una pregunta, es suficiente implementar la energia para que ocurra la minimización? (va a buscar una solucion que cumpla con gastar la energia inicial) o se busca que usemos ```#minimize``` para que se gaste a menor energia?

**Comment by MelanyLillo** [comment]
Hola! Podría un robot usar menos energía de la entregada?
