### ISSUE TITLE
DCCarrybot 2.1: Caja cambia de posición sin ser antes levantada por un robot

### ISSUE THREAD

**Issue by dedmu5** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#30]
Básicamente lo que dice el título. La caja se teletransporta sin que un robot la tome.

![imagen](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/65060602/50787452-7612-43f6-b9a1-588078174796)
![imagen](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/65060602/979dae19-54bf-434d-be90-8a6f81db6bbf)

Estoy usando el test_D1 con bound=7
Este es mi modelo:

```
Answer: 1
rangeX(0) rangeX(1) rangeX(2) rangeY(0) rangeY(1) time(1) time(2) time(3) time(4) time(5) time(6) time(7) goal(2,1) boxOn(0,1,0,0,0) robotOn(0,0,0,0,3) boxOn(0,1,0,0,1) boxOn(0,1,0,0,2) boxOn(0,1,0,0,3) boxOn(0,1,0,0,4) robotOn(0,0,0,1,2) robotOn(0,0,1,2,2) boxOn(0,1,0,0,5) boxOn(0,1,0,0,6) robotOn(0,1,1,6,4) robotOn(0,1,1,4,4) robotOn(0,1,1,5,2) robotOn(0,0,1,3,4) robotOn(0,1,1,7,4) robotOn(0,2,1,7,4) robotOn(0,0,1,7,3) robotOn(0,1,1,6,3) robotOn(0,1,1,7,3) boxOn(0,1,1,1,7) boxOn(0,0,1,1,7) boxOn(0,2,1,1,7)
SATISFIABLE

Models       : 1+
Calls        : 1
Time         : 0.180s (Solving: 0.08s 1st Model: 0.01s Unsat: 0.00s)
CPU Time     : 0.016s
```

Este es mi output.txt

```
2,1
7
E,2,1
R,0,0,0,0,3
R,0,0,0,1,2
R,0,0,1,2,2
R,0,0,1,3,4
R,0,1,1,4,4
R,0,1,1,5,2
R,0,1,1,6,4
R,0,1,1,6,3
R,0,1,1,7,4
R,0,2,1,7,4
R,0,0,1,7,3
R,0,1,1,7,3
C,0,1,0,0,0
C,0,1,0,0,1
C,0,1,0,0,2
C,0,1,0,0,3
C,0,1,0,0,4
C,0,1,0,0,5
C,0,1,0,0,6
C,0,1,1,1,7
C,0,0,1,1,7
C,0,2,1,1,7
```

Gracias de antemano

**Comment by dfloreaa** [comment]
Hola, esto debe ser debido a un error de tu programa. No se qué esperas que pueda contestar en la issue.

Saludos ✨

**Comment by dedmu5** [comment]
> Hola, esto debe ser debido a un error de tu programa. No se qué esperas que pueda contestar en la issue.
> 
> Saludos ✨

Es que estoy confundido porque en esta parte de la tarea se me pide modelar el movimiento de direccionalidad del robot, no definir las reglas que hagan que las cajas no se teletransporten. Si las cajas están comportándose así significa que debo añadir una restricción para que no se teletransporten (además de mi código de direccionalidad)?

**Comment by dfloreaa** [comment]
La regla se encuentra implementada anteriormente, tienes que tener ojo en que ahora los robots deben estar mirando a una caja para recogerla. Quizás es en esta parte de tu implementación que la lógica del funcionamiento de las cajas empezó a fallar (dado que en el código base no lo hace).

**Comment by dedmu5** [comment]
> La regla se encuentra implementada anteriormente, tienes que tener ojo en que ahora los robots deben estar mirando a una caja para recogerla. Quizás es en esta parte de tu implementación que la lógica del funcionamiento de las cajas empezó a fallar (dado que en el código base no lo hace).

Eso es lo que me confunde. Como arreglar nuevas reglas puede hacer que otras cosas que si funcionaban ya no funcionen? Por lo que entiendo de clingo, si añado nuevas reglas sin borrar las anteriores solo estaría "filtrando" los modelos de la versión antigua. Es decir, si en la versión antigua tengo una restricción para que las cajas no se teletransporten, no puedo añadir una regla que haga las cajas se teletransporten, porque sería una contradicción lógica.

**Comment by dfloreaa** [comment]
> Eso es lo que me confunde. Como arreglar nuevas reglas puede hacer que otras cosas que si funcionaban ya no funcionen? Por lo que entiendo de clingo, si añado nuevas reglas sin borrar las anteriores solo estaría "filtrando" los modelos de la versión antigua. Es decir, si en la versión antigua tengo una restricción para que las cajas no se teletransporten, no puedo añadir una regla que haga las cajas se teletransporten, porque sería una contradicción lógica.

Hola, este no es el caso. Tengo entendido que vieron en clases como es que Clingo encuentra soluciones, pero en caso contrario, debes saber que las reglas no actuan de forma secuencial, por lo que añadir una nueva regla si puede abrir a nuevos modelos para un programa.

Habiendo dicho eso, te recomiendo **fuertemente** revisar los cambios que hiciste al código base, especialmente en la interacción robot-caja.

Un saludo ✨

**Comment by dedmu5** [comment]
> > Eso es lo que me confunde. Como arreglar nuevas reglas puede hacer que otras cosas que si funcionaban ya no funcionen? Por lo que entiendo de clingo, si añado nuevas reglas sin borrar las anteriores solo estaría "filtrando" los modelos de la versión antigua. Es decir, si en la versión antigua tengo una restricción para que las cajas no se teletransporten, no puedo añadir una regla que haga las cajas se teletransporten, porque sería una contradicción lógica.
> 
> Hola, este no es el caso. Tengo entendido que vieron en clases como es que Clingo encuentra soluciones, pero en caso contrario, debes saber que las reglas no actuan de forma secuencial, por lo que añadir una nueva regla si puede abrir a nuevos modelos para un programa.
> 
> Habiendo dicho eso, te recomiendo **fuertemente** revisar los cambios que hiciste al código base, especialmente en la interacción robot-caja.
> 
> Un saludo ✨

Gracias por la aclaración, creía que funcionaba de otra forma. En todo caso, leyendo de nuevo el enunciado me doy cuenta que el caso que me ocurre no se contradice con el enunciado. Es decir, no existen reglas que restrinjan el movimiento de una caja que no está siendo llevada por un robot (Z=0). Está mal si creo una regla para que esto no ocurra?

**Comment by dfloreaa** [comment]
No, siéntete libre de crear esas reglas. Saludos
