### ISSUE TITLE
Control Corto 2

### ISSUE THREAD

**Issue by vjimenezs** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#32]
Hola!

Perdón por preguntar un sábado, me surgió la duda en base al anuncio enviado hoy sobre el control del lunes. Quería preguntar si se va a subir algún material sobre la materia de Introducción a la búsqueda (tengo entendido de lo que aparece en el repo que la Ayudantía 4, del 8/09/2023, fue de Intro a la búsqueda). En caso de que no se vaya a subir, quería consultar por alguna recomendación sobre qué contenidos buscar para mi estudio.

De antemano muchísimas gracias! :)

**Comment by dfloreaa** [comment]
Hola, lamentablemente por temas personales no he podido actualizar los apuntes del curso con la unidad de búsqueda :(

Les recomiendo estudiar la naturaleza de un problema de búsqueda y sus componentes (agente(s), estados, configuraciones, etc) y los algoritos de DFS y BFS.

Saludos ✨
