### ISSUE TITLE
Pregunta Cálculo de Heurísitcas

### ISSUE THREAD

**Issue by StoicSilver** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#35]
Si yo tengo una heurísitca donde para todo estado  **s** el valor es 1, sin cambiar su valor al moverse entre estados. Se podría decir que esta es **admisible**?  Ya que nunca va a superar el valor de la heurísitca ótpima. Y, es posible definir una heurísitca de esa manera? 

De antemano, muchas gracias.

**Comment by dfloreaa** [comment]
Hola, su único problema sería estimar 1 para estados finales de la ejecución. Otro supuesto es que los costos siempre serán >= 1, pero sí.
