### ISSUE TITLE
T3-2.2: Corriendo el código para h3.

### ISSUE THREAD

**Issue by andresmoraga0** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#36]
Hola! Estaba implementando la heurística h3, pero al correr el siguiente código:
`python3 game/run.py astar tests/test7.txt h3 1`

Obtengo el siguiente error:

`Traceback (most recent call last):
  File "/Users/andresmoraga0/Desktop/IA/t3-2023-2-andresmoraga0/DCCarJam/game/run.py", line 25, in <module>
    final_node = solver.search()
  File "/Users/andresmoraga0/Desktop/IA/t3-2023-2-andresmoraga0/DCCarJam/game/solver.py", line 29, in search
    initial_node.h = self.initial_state.heuristic()
AttributeError: 'Board' object has no attribute 'heuristic'. Did you mean: 'set_heuristic'?`

el cual no termino de entender, ya que incluso si decido copiar h0 en h3 me sigue apareciendo, pero cuando corro usando h0, h1 y h2 funciona perfectamente. No descarto que sea evidente la respuesta, pero ahora mismo no entiendo muy bien por qué no me corre.

Muchas gracias de antemano!

**Comment by PkAlvaro** [comment]
Añade a la función set_heuristic lo relacionado a h3, es básicamente añadir un elif más.

**Comment by dfloreaa** [comment]
Exactamente, lo que comenta @PkAlvaro
