### ISSUE TITLE
Valor de costos DCCarJam

### ISSUE THREAD

**Issue by Aledgit** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#37]
En el problema 2.1. 2. para explicar que son consistentes las heurísticas es necesario que h(s) <= c(s, s') + h(s'). 
Si h(s') < h(s) entonces la desigualdad depende de c(s, s'), pero ese valor no está explícito en ninguna parte del enunciado y me cuesta deducirlo del código. Puedo asumir un valor conveniente? O asumir que cada acción tiene costo 1?.

**Comment by dfloreaa** [comment]
Hola, no me queda claro a que te refieres.

Para h(s) <= c(s, s') + h(s'):
- s es un nodo cualquiera al que buscamos estimar el costo de llegar
- s' es otro nodo en el camino hacia s
- h(s') es la estimación de costo hasta s'
- c(s, s') es el costo real de moverse desde s' hasta s

Si esa no era tu duda, por favor clarifícamelo aquí abajo.

Un saludo
