### ISSUE TITLE
SuperGato 3.1

### ISSUE THREAD

**Issue by MelanyLillo** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#38]
Hola! Para la parte 3.1 de la tarea ¿cómo puedo ver que la implementación funciona correctamente?

**Comment by dfloreaa** [comment]
Hola, puedes probar jugando partidas contra el algoritmo o bien debuggear mediante prints su logica de funcionamiento.

Saludos ✨

**Comment by MelanyLillo** [comment]
Ok, pero en caso de que haga competir a dos IA, podría obtenerse cualquier resultado?

**Comment by ignaciovilla** [comment]
Hola! Cualquiera de las dos IA podría ganar o incluso pueden empatar.
