### ISSUE TITLE
Super Gato 3.1

### ISSUE THREAD

**Issue by STageAmp** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#40]
Hola,

Estoy teniendo problemas con mi código de Minimax. El problema principal es que la posición devuelta durante las llamadas recursivas siempre es "None", y la ejecución de mi bucle continúa indefinidamente.

Estoy tratando de averiguar si esto se debe a una mala implementación de la función "contar_tableros_diferencias" o si estoy utilizando incorrectamente esta función en mi programa principal de pruebas, donde hago que dos IA jueguen entre sí o hagan que una IA juegue contra un humano.

Si tienes algún consejo o sugerencia sobre cómo abordar este problema, te agradecería mucho tu ayuda.

**Comment by dfloreaa** [comment]
@STageAmp el problema que logré ver le ha ocurrido a más gente así que aprovecharé de comentarlo por aquí.

Al ejecutar el algoritmo Minimax debes recordar que en cada paso de profundidad alternaremos entre escoger el movimiento que maximiza el valor para nuestro agente y escoger aquel que lo minimiza (asumimos que el oponente juega el movimiento que más nos perjudica en su turno).

Por tanto, su ejecución se vería algo así:
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/62019645/e80889a8-819d-41fd-a8a1-8366f52b135f)

Por tanto, en la función `minimax()`, en cada paso que maximizamos (`if maximizar:`), la llamada siguiente deberá **minimizar** el score para nuestro jugador. Similar para cada paso en que minimizemos (`else:`), donde la siguiente llamada recursiva buscará **maximizar** el score para nuestro agente.

Espero que esto les ayude con el desarrollo de su tarea, un saludo ✨😊

**Comment by STageAmp** [comment]
Gracias por eso, en efecto no lo habia considerado. 

Ahora hizé la correccion y me parece correcto el codigo de minimiax. Lo que parace extrano es que la implementacion parece funcionar solo cuando uso la funcion minimax con "false" por los dos jugadores en el main... 

A demas, tengo una otra pregunta : al principio quisiera implementar el main de test con una bucla for que implementa los 5 ejecuciones del algoritmo, pero el programma se demorra demasiado y despues de la segunda, tercera o cuarto ejecucion, hay un bug total..... Eso se puede por razon de la complejidad del codigo (los llamados recursivos son causas de muchos bugs) ? 
O eso no deberia ser posible ? 
Sino, puedo usar 5 veces el main de manera singular para la misma profundidad y presentar los resultados ? 

(yo subo los codigos actualizados por si acaso)

**Comment by dfloreaa** [comment]
@STageAmp ambos jugadores deben partir maximizando en la llamada a minimax, esto debido a que llevarán a cabo la búsqueda en su turno, por lo que escogerán el mejor movimiento posible. En caso contrario estarían haciendo el peor movimiento de forma consciente en cada jugada.

Dudo que el código genere problemas por la profundidad de la recursión, dado que cada partida es independiente del resto y no se juegan en paralelo, en todo caso, recomiendo no modificar mucho el main y simplemente ejecutarlo 5 veces.

Saludos ✨
