### ISSUE TITLE
A* 1.1

### ISSUE THREAD

**Issue by nicoolivaresm** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#41]
Hola, me surgió una duda respecto a los costos. ¿Estos tienen alguna restricción sobre su valor?, es decir si es que son mayores/igual que cero, en los reales, etc.

**Comment by dfloreaa** [comment]
Hola, dado que el costo de hacer un movimiento es 1, debes tener en cuenta que no se pueden llevar a cabo movimientos negativos, por lo que los costos siempre serán $\geq 0$. Si bien la heurística puede estimar mediante valores decimales también, el costo real para llegar a un nodo será entonces siempre un número entero.
