### ISSUE TITLE
Consulta SuperGato alpha y beta

### ISSUE THREAD

**Issue by jicartagena** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#42]
Hola! simplemente es que no entiendo la función de las variables alpha y beta. Viendo todo el codigo solo es creado como inf y mencionado como 'poda' pero no entiendo el significado de esto. Se dice que hay que actualizar el puntaje y posicion en la parte 1, imagino que esto igual debe ser contado?

**Comment by dfloreaa** [comment]
Hola, estas variables son utilizadas para llevar a cabo la poda alfa-beta en la búsqueda, optimizándola y ahorrando expansiones innecesarias. Ahora bien, decidimos remover este ejercicio de la tarea, por lo que simplemente ignóralas.

Saludos ✨

**Comment by jicartagena** [comment]
Super! gracias
