### ISSUE TITLE
[T3] contar_tableros_diferencia (score.py)

### ISSUE THREAD

**Issue by vjimenezs** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#43]
Hola! Me surgió una duda con respecto a la función `contar_tableros_diferencia`. He estado probando, y por lo menos en mi código, nunca entra a estos `if`

```
def contar_tableros_diferencia(tablero, ficha) -> int:
...
        if ficha == 1 and contar_ficha_1 > contar_ficha_2:
            tableros_con_diferencia += 1
        elif ficha == 2 and contar_ficha_2 > contar_ficha_1:
            tableros_con_diferencia += 1
```

Es posible que envés de `ficha == 1` debería ser `ficha == "X"`? Realizando ese cambio (y el análogo para O), sí me da valores diferentes a 0, pero con el código actual noto que está retornando siempre 0 (y tomando decisiones no óptimas en base a ese valor).

Tampoco sé si puede ser un problema de cómo yo he implementado minimax.

Gracias:)

**Comment by dfloreaa** [comment]
Hola, efectivamente, parece que hubo una confusión con los valores de las variables, por favor cámbialo. Si no alcanzan a hacerlo será considerado en la corrección.

Un saludo
