### ISSUE TITLE
Costo de heuristica en DCCarJam

### ISSUE THREAD

**Issue by vcrb18** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#44]
Tengo una duda con como podemos ver el costo en esta tarea. Especialmente quiero explicar mi duda con el ejercicio 2.1 con la heurística h1. Si h1 es la distancia desde el auto rojo a la salida y digamos que `h(s) = 3` y `h(s') = 2`, para que se cumpla la inecuación, el costo `c(s, s')` tiene que ser mayor o igual que 1 para que la heurisística sea consistente.
Puede verse entonces el costo como el número de movimientos por ejemplo? En el caso que s' sea una ubicación a la derecha que s, entonce la inecuación:
```
h(s) <= c(s, s') + h(s')
3 <= 1 + 2
3 <= 3
```
Y esto solo sería consistente en caso que `c(s, s') >= 1`, lo cual si no es el número de movimientos por ejemplo, no tengo la seguridad si siempre se cumple.

**Comment by dfloreaa** [comment]
Efectivamente, el costo hace referencia a la cantidad de movimientos necesarios para llegar de un estado a otro.

Saludos ✨
