### ISSUE TITLE
[3.1] Retorno de funcion minimax para profundidad 0

### ISSUE THREAD

**Issue by nicomeiser** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#46]
Holaaa
En el codigo entregado cuando llegamos a profundidad 0 es 
else:  # Profundidad es 0
            if maximizar:
                return (None, funcion_puntaje(tablero, ficha))
            else:
                return (None, -funcion_puntaje(tablero, ficha_oponente))

Pero según yo debería ser: 
else:  # Profundidad es 0
            if maximizar:
                return (None, -funcion_puntaje(tablero, ficha_oponente))
            else:
                return (None, funcion_puntaje(tablero, ficha))

Por ejemplo, con profundidad 3:
max, 3 --> min, 2 --> max, 1 --> min, 0
Luego (con la implementación actual) min, 0 le retorna -funcion_puntaje(tablero, ficha_oponente) a el max, 1 
Por lo tanto, el max, 1 está eligiendo valores negativos y los valores dependen de la función puntaje de la ficha del oponente.

Me hace más sentido que min, 0 le retorne funcion_puntaje(tablero, ficha) a el max,1 así el que está maximizando elije la jugada que le entregue un mayor puntaje según la función puntaje de su ficha.

**Comment by ignaciovilla** [comment]
Hola! Efectivamente está mal, pero debería ser:

else: # Profundidad es 0
    if maximizar:
         return (None, funcion_puntaje(tablero, ficha))
    else:
         return (None, funcion_puntaje(tablero, ficha_oponente))

Es decir, sin el signo "-" en ninguno de los casos. Por otro lado, si es que ya hicieron esta parte no se preocupen, lo importante es el análisis sobre los resultados que hicieron.
Espero eso haya respondido tu duda. Cualquier cosa avísame.
