### ISSUE TITLE
2.2.3 Duda tests

### ISSUE THREAD

**Issue by nicolaspoli** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#48]
Hola! 

Se espera que para la tabla con los resultados se revisen los test del 1 al 7 y ademas los "anytime"? o solo los numerados?

Gracias de antemano!

**Comment by dfloreaa** [comment]
Hola, con solo los test numerados está bien, la idea es estudiar tendencias.

Un saludo ✨

**Comment by nicolaspoli** [comment]
gracias!
