### ISSUE TITLE
Duda con un error al correr las heurísticas

### ISSUE THREAD

**Issue by FabriRandon** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#49]
Hola buenas, estoy intentando correr el código para poder probar las heurísticas con A* pero me tira el siguiente error.

![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/101484224/f87cabcd-2266-4cb2-988d-09ff366944bd)

¿Cómo podría solucionarlo?

Gracias.

**Comment by dfloreaa** [comment]
Cambia la línea por
`print(f'Found a solution in {len(moves)} moves!')

Debería funcionar, me avisas
Saludos✨

**Comment by FabriRandon** [comment]
Al final era porque tenía instalado python 2, me cambié a python 3 y todo se arregló. Dejo esta información por si a alguien más le ocurre. Gracias igual!!! Saludos.
