### ISSUE TITLE
Tests DCCudoku

### ISSUE THREAD

**Issue by MelanyLillo** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#5]
Hola! Cuál es el comando para probar los tests del DCCudoku? Noté que sale la forma de generar el archivo output.json, pero no se indica cómo probar cada test.

**Comment by dfloreaa** [comment]
Hola, puedes probar el test seleccionando el archivo `output.json` en el visualizador y revisando de que el orden sea correcto.

Un saludo :)

**Comment by MelanyLillo** [comment]
Hola, me refiero a si tengo que escribir mi solución en cada archivo de test y luego usar este para generar output.json o si los test están ya implementados en el visualizador. Hasta ahora he comprobado mediante consola que mi código entrega bien el modelo, pero al generar output.json solo dice null debido a que no se detecta el tamaño de la grilla.

**Comment by dfloreaa** [comment]
Hola, en la issue #10 estamos revisando el mismo problema, por favor te pido mantenerte al tanto en ella (seguimos tratando de encontrar el problema).

Un saludo ✨! :)

**Comment by MelanyLillo** [comment]
Hola! Ahora si me toman las soluciones, sin embargo, aún no puedo usar el visualizador porque el tamaño de la grilla me aparece como 0. Al hacer print(content) me aparece lo siguiente:
![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/110860215/0a1e0ebc-1f93-4d86-aed1-b2dcc35452b3)

**Comment by a-ck** [comment]
a mí igual me pasó, tuve que hardcodear el grid size
