### ISSUE TITLE
3.1 Verificar implementacion

### ISSUE THREAD

**Issue by STageAmp** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#50]
La verdad es que no es muy claro para mi como debemos mostrar que la implementacion de minimax funciona : 
- debemos hacer 5 ejecuciones del algoritmo y dar el ganador de cada ejecucion : eso significa que debemos lanzar un partida entre dos jugadores 
               - si hacemos jugar dos IA, el ganador puede ser una o otra y no tiene tan importancia el ganador para mostrar que el AI con minimax no es vencible 
               - si hacemos jugar 1 IA con minimax en frente a un humano, el tiempo de ejecucion (para terminar el partida) depende del tiempo que toma el humano para jugar asi no es concluyente

A demas debemos mostrar que el IA no es vencible con minimax ? A mi me paso que es muy facil ganar como humano. 
Debemos medir el tiempo de ejecucion del algoritmo minimax con distintas profundidades O de un partida completo con distintas profundidades ?

**Comment by ignaciovilla** [comment]
Hola! Da lo mismo quien gane, lo importante es que se vea que el algoritmo funciona (la función de puntaje solicitada no es necesariamente óptima por lo que probablemente le ganen como humanos) . Por otro lado, se espera que hagan jugar una IA contra otra y ver que pasa (si hicieron una IA vs un humano no se preocupen) e ir variando las profundidades. La idea es que puedan ver el cambio de tiempo de ejecución al aumentar la profundidad del algoritmo y explicar a que se debe esto.
Espero eso haya solucionado tu duda. Avísame cualquier cosa.

**Comment by M4rtinL4gies** [comment]
Hola! Me quedan dudas respecto al estudio para la verificación. Al hacer jugar una IA contra otra, ¿la idea es aumentar la profundidad de ambas (estudiar qué pasa cuando ambas tienen profundidades de 1, 3 y 5) o mantener una fija y aumentar la profundidad de la otra?

**Comment by ignaciovilla** [comment]
Para esta pregunta deben aumentar ambas al mismo tiempo.

**Comment by M4rtinL4gies** [comment]
Gracias!
