### ISSUE TITLE
Problema implementación MINMAX

### ISSUE THREAD

**Issue by tsunayoshi21** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#51]
Hola, estoy teniendo problemas al verificar la implementación de mi algoritmo minmax. Al ejecutar el main.py con 2 IAS o con 1 IA y un Random, en los movimientos de la IA nunca se converge a un valor de puntaje correcto, y siempre oscila entre -inf y 0 en un bucle infinito.

Leí todas las issues con este problema y no pude encontrar nada para mi problema.
Adjunto foto de prints de puntajes de los minmax (puntaje1 y posicion1 son para el MIN).

![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/69870567/b7df97f9-75d8-492a-8b83-3d439d18071e)

Agradecería si me pudieran orientar un poco con esto, ya que según mi razonamiento debería funcionar bien, pero claramente no es el caso.

**Comment by STageAmp** [comment]
Me paso esto cuando habia puso "True" or "false" en mi funcion minimiax en los llamados recursivos y cuando reemplazé por "maximizar" o "not maximizar" era bueno.

**Comment by dfloreaa** [comment]
@tsunayoshi21 sirvió de algo la recomendación de tu compañera? En caso contrario y que sigas trabajando en tu tarea, mantenme al tanto.

**Comment by tsunayoshi21** [comment]
@dfloreaa Hola, sigo trabajando en la tarea y pude finalmente hacer que corriera el minmax pero no estoy seguro si es que esta computando correctamente. Digo esto porque si bien corre, luego utilizando las disitinas funciones de puntaje, tengo muchos empates, y por ejemplo me sale que es mejor la funcion contar tableros diferencia, lo que para mi es raro porque siento que tiene mucho más sentido que gane la funcion de contar fichas seguidas. 

Acabo de commitear mis avances con todo. Me podrías dar algo de feedback sobre mi función minmax? creo que es lo único que podría estar fallando (si es que esta fallando porque me hace sentido que este bien, solo no me hacen sentido los resultados)
