### ISSUE TITLE
Clarificación sobre la medición del tiempo de ejecución Super Gato 3.1

### ISSUE THREAD

**Issue by OscarCampohermoso** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#52]
Tengo una duda respecto a la medición del tiempo de ejecución en la parte del Super Gato. En el documento se menciona que, para cada profundidad, debemos indicar para cada partida la ficha ganadora y el *tiempo de ejecución*, además del *tiempo total* de las 5 ejecuciones.

Mi pregunta es: ¿Debemos crear una implementación propia para calcular este *tiempo de ejecución* o hay alguna recomendación o método preferido que deberíamos utilizar? No me queda claro si la intención es que desarrollemos nuestro propio método o si hay alguna herramienta o práctica estándar que se espera que utilicemos.

**Comment by vcrb18** [comment]
Me sumo a la pregunta de mi compañero

**Comment by ignaciovilla** [comment]
Hola! Pueden usar la librería time de python.
Avísenme cualquier duda.
