### ISSUE TITLE
Chequeo Nodos Terminales Minimax

### ISSUE THREAD

**Issue by M4rtinL4gies** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#53]
Para la actividad 3.2.1, una de las reglas para la función de puntaje es que si una ficha gana el juego entonces suma 15 puntos. Revisando los resultados de mi programa noté que la IA tiene problemas para realizar el movimiento ganador (no pareciera ver que le entrega 15 puntos extra ganar). Revisando el código de Minimax vi que en caso de encontrar un nodo terminal siempre se asignan puntajes de infinito o menos infinito, sin evaluar la función de puntaje. Luego, hay dos cosas que no logro comprender:

1. De qué forma podemos darle los 15 puntos a la IA si se le asignan infinitos puntos si gana.
2. Por qué, si se le están asignando infinitos puntos al ganar, le cuesta tanto a la IA finalizar el juego.

Es muy probable que esté malinterpretando algo del código y agradecería recibir ayuda al respecto :).

**Comment by ignaciovilla** [comment]
Hola!
1. Tienes que hacerlo a la hora de evaluar el estado del juego (a la función de puntaje le entra el estado del juego como input). 
2. Puedes pensar que para el agente minimax su función de puntaje es la forma en que el agente "mira el mundo", por lo que puede ser que en ese mundo el obtenga infinito puntaje, pero la función de puntaje probablemente no es óptima, por lo que a pesar de que se le están asignando infinitos puntos por ganar en ese mundo, no necesariamente ganará siguiendo esa estrategia en el mundo real.

Espero que eso clarifique tu duda. Avísame cualquier cosa.

**Comment by M4rtinL4gies** [comment]
Perfecto, el punto 2 me quedó claro. Sigo teniendo dudas con el punto 1 eso sí. Entiendo que le entregamos el estado del juego como input a la función, pero según entiendo, debido a la forma en la que estamos llamando a la función, cuando encontremos un estado terminal no podremos asignar 15 puntos extra, porque siempre le estaremos asignando infinito (por el orden del código en la función Minimax).
