### ISSUE TITLE
T3 -  sobre "estudio.pdf"

### ISSUE THREAD

**Issue by andresmoraga0** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#54]
Hola!

Duda cortita. En la parte 3 nos piden poner los análisis de la pregunta en un archivo llamado `estudio.pdf`, pero ya vamos a tener un archivo pdf con los análisis de las preguntas anteriores. ¿Será necesario tener este archivo aparte, o simplemente lo puedo poner en el archivo .pdf con el resto de la tarea?

Saludos!

**Comment by ignaciovilla** [comment]
Hola! Mientras quede ordenado y claro puedes hacerlo junto.

**Comment by andresmoraga0** [comment]
Gracias!
