### ISSUE TITLE
T3 error importante en contar_tableros_diferencia

### ISSUE THREAD

**Issue by ndelpiano** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#55]
Hola, creo que encontre un error en la funcion contar_tableros_diferencia.
Codigo:
def contar_tableros_diferencia(tablero, ficha) -> int:
        if ficha == 1 and contar_ficha_1 > contar_ficha_2:
            tableros_con_diferencia += 1
        elif ficha == 2 and contar_ficha_2 > contar_ficha_1:
            tableros_con_diferencia += 1

En esta parte de la funcion se usa el parametro ficha como si fueran numeros, pero el parametro es entregado como O o X, lo que hace que nunca se cumpla la condicion. Probe poniendo un print dentro del if y nunca se printea al correr el codigo. Si no estoy equivocado, muchas personas pueden haber seguido el ejemplo de la funcion y todo su codigo este malo.

**Comment by dfloreaa** [comment]
Hola, ya fue comentado y marcado como importante en la issue #43 

Saludos
