### ISSUE TITLE
Duda sobre los cupones

### ISSUE THREAD

**Issue by FabriRandon** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#57]
Hola,

Tengo dudas con respecto a los cupones.

Si uno no gasta ningún cupón, existe algún beneficio asociado a ello a fin de semestre como un incentivo para entregar a tiempo?

Si no es así, existe alguna posibilidad de conversación o algo para que implementen algún bonus por cupón no utilizado?

**Comment by dfloreaa** [comment]
Hola, no, no hay beneficio asociado a no utilizar los cupones.

Se tratan de un recurso que brindamos para ayudarles en caso de que complicaciones externas les eviten completar sus tareas en el plazo original y así no descuidar su bienestar. Recompensarles por no utilizarlos va completamente en contra de esta idea al incitarlos a no hacerlo (úsenlos, por algo los creamos :) ).

**Comment by FabriRandon** [comment]
Valee, gracias, más que nada preguntaba porque es común en ramos del DCC la dinámica de cupones con posibilidad de bonus en caso de no uso. Agradezco la información y la creación de ellos en pro de nuestro bienestar. Haré uso de ellos entonces.

Saludos.
