### ISSUE TITLE
Duda encoding csv

### ISSUE THREAD

**Issue by claudiosalvador** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#58]
Estaba tratando de abrir el csv y me dio un error de encoding (UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 11: invalid start byte) y al visualizar el archivo tengo esto:

![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/48532736/09a58e17-075b-4c28-9552-e098d5fb94b2)

Me imagino que esto no es lo esperado o si?

**Comment by dfloreaa** [comment]
Hola, el archivo `.csv` [fue corregido en el repositorio base de la tarea](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/T4/blob/master/IMDB.csv), así como fue comentado en el anuncio enviado por Canvas.

Saludos ✨
