### ISSUE TITLE
1.6. Cálculo de métricas 

### ISSUE THREAD

**Issue by bernirosas** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#59]
Hola! para el cálculo de métricas se puede hacer la tabla más a mano? que colab no aguanta mucho tiempo antes de reinciarse así que está difícil formarlo con los datos reales pero puedo sacar el de cada uno e irlo agragando.

**Comment by bernirosas** [comment]
Ok, sacaré los pantallazos, gracias. ¿Los dejo en el informe me imagino?
Saludos

**Comment by dfloreaa** [comment]
Si, también puedes pegarlos en el notebook, en las celdas anteriores a la tabla. Queda a tu criterio ;)
