### ISSUE TITLE
1.2.3 Librería NLTK

### ISSUE THREAD

**Issue by nicoolivaresm** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#60]
Holaa, estoy teniendo problemas con la librería NLTK y no se porque. Ya la instalé en mi computador, y la importe en el código pero me genera una error de certificado fallido (adjunto imagen). 

<img width="1440" alt="Captura de pantalla 2023-11-08 a la(s) 12 31 45" src="https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/106032490/770714cd-3871-4c9d-89dd-0559493a32e8">

**Comment by renatoqueirolo** [comment]
Hola, lo pudiste solucionar? Tengo el mismo problema

**Comment by dfloreaa** [comment]
Hola, aparentemente se trata de un problema directamente de la librería `nltk` al trabajar en algunos directorios de mac, debería poder arreglarse al deshabilitar el checkeo de SSL añadiendo las siguientes líneas antes:

```
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download()
```

Un saludo, avísame si se arregla ✨
