### ISSUE TITLE
Clasificador - SVM

### ISSUE THREAD

**Issue by IgnaciaJ** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#61]
Hola! llevo un rato intentando de correr el clasificador SVM con cada uno de los resultados entregados en la parte de vectorización pero el tiempo de ejecución de cada uno está siendo muuy grande(cercanos a 1hr), nose como puedo disminuir el tiempo de ejecución, ¿alguna recomendación?

**Comment by bernirosas** [comment]
Me uno preguntando si se le puede bajar un poco la cantidad de datos.

**Comment by dedmu5** [comment]
Me uno preguntando si se le puede bajar un poco la cantidad de datos.

**Comment by dfloreaa** [comment]
Hola, sí, permitiremos entrenar con los 5000 datos de cada clase que se especifican en las preguntas anteriores, ojalá eso reduzca el tiempo de entrenamiento.

Un saludo

**Comment by dedmu5** [comment]
> Hola, sí, permitiremos entrenar con los 5000 datos de cada clase que se especifican en las preguntas anteriores, ojalá eso reduzca el tiempo de entrenamiento.
> 
> Un saludo

Hola Daniel,
Yo tuve que hacer malabares para que me funcionara entrenar con 3000 datos por clase. El problema es que tengo un PC con 8 GB de RAM, por lo que sin ejecutar nada tengo menos de 1 GB libre
![imagen](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/65060602/1be4bfa0-4d69-4995-8876-35c6c6f95a14)
Ya de por sí la extracción de características con TF-IDF utilizando 5000 datos utiliza como 1.3 GB de memoria por lo que no pude entrenar  nunca con 5000. Ya prácticamente terminé la tarea y obtuve accuracys mayores a 80% en todos los modelos excepto 1. Existe algún problema con entregar la tarea utilizando los 3000 datos?

Saludos

**Comment by dfloreaa** [comment]
Hola, por favor detallalo en tu entrega, tanto en pdf como en comentarios sobre el codigo. En caso de tener limitaciones de hardware lo permitiremos

Saludos :) ✨
