### ISSUE TITLE
1.3 y 1.4 Vectorizacion y Clasificadores

### ISSUE THREAD

**Issue by LucasReds** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#62]
Estoy intentando vectorizar pero me tira error al tratar de guardar las dataframes de cada tipo :

MemoryError: Unable to allocate 30.4 GiB for an array with shape (101893, 40000) and data type int64

Podria usar menos datos para los vectores? O es necesario usar todo?

**Comment by dedmu5** [comment]
probablemente no reduciste los datos a 5000 por clase

**Comment by dfloreaa** [comment]
Hola, el dataframe con que trabajas es muy grande dado que utilizas todos los datos, como comentan anteriormente, usa 5000 datos de cada clase solamente para este ejercicio.

Saludos
