### ISSUE TITLE
Pregunta sobre la forma de la entrega

### ISSUE THREAD

**Issue by STageAmp** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#64]
Hola, 
Creo que el orden de las preguntas en el notebook de origen complica nuestro código y me gustaría poder calcular las métricas de cada modelo directamente durante su entrenamiento (sección 1.4) y solo mostrar la comparación de estas métricas en la sección 1.6. Del mismo modo, me gustaría llamar a Lime directamente en la sección 1.4 y mostrar el resultado en la sección 1.5. ¿La corrección nos penalizará en este caso? 
Además, debido al tiempo de cálculo demasiado largo con 50,000 datos, elegí entrenar los modelos con una cantidad de datos de 5,000 por categoría. El problema es que el tiempo seguía siendo demasiado largo para la vectorización Sbert y para el entrenamiento del SVM. Entonces tuve que reducirlo a 2,500 datos por categoría, y por una cuestión de comparación objetiva entre los modelos, creo que lo mejor es usar esta cantidad de datos (5,000 en total) para los 9 modelos. ¿Es posible o habrá una penalización aplicada?

Gracias de antemano por su consideracion,

**Comment by dfloreaa** [comment]
Hola, no hay problema con calcular el desempeño en 1.4 y luego solamente comentarlo. En el caso de LIME seria preferente que si lo lleves a cabo en la sección específica.

Mientras comentes en tu entrega el motivo, no hay problema con utilizar menos datos, recuerda eso si que debe estar justificado acordemente.

Saludos ✨
