### ISSUE TITLE
Consulta de LimeTextExplainer

### ISSUE THREAD

**Issue by searzola** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#65]
Hola, realicé la modificación que se indica en el anuncio de fix para la T4, pero me queda la duda de cómo utilizar con estos datos el explainer, ya que requiere un input de texto y las salidas del split entre train y test son matrices de numpy.

**Comment by dfloreaa** [comment]
Luego de generar una instancia de `LimeTextExplainer`, debes utilizar el método `explain_instance` de la clase con argumentos correspondientes a qué dato clasificar (la fila del DataFrame), una función que reciba el texto y retorne la predicción con probabilidad para ese dato (hint: usa `predict_proba(vectorized_text)`) y num_features equivalente al número de features que buscas que utilize LIME para hacer su explicación, por ejemplo, 6.

Espero que te aclare la duda.
Saludos ✨
