### ISSUE TITLE
Valor hiperparámetros de los modelos

### ISSUE THREAD

**Issue by annaramon** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#66]
El valor de los hiperparámetros de los diferentes modelos, ¿puede ser por default o se recomienda aplicar una Grid Search para cada uno? Traté de aplicar una Grid Search para cada uno, pero se demora demasiado.

**Comment by dfloreaa** [comment]
Hola, puede ser el default. Se recomienda ajustarlos a mano solo en caso de tener el tiempo.

Saludos ✨
