### ISSUE TITLE
Definición de Up y Down

### ISSUE THREAD

**Issue by kolk3y** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#7]
¡Hola! ¿Existe la posibilidad de que esto esté mal definido?

![imagen_2023-08-28_220441078](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/105676376/011982e5-f9d6-4d33-a236-6192c180a10c)

Si para moverse arriba se debe sumar 1 a la coordenada Y, entonces en la imagen adjunta el robot no se estaría moviendo hacia arriba, sino que hacia abajo. Viceversa sucede el mismo problema, si el robot en (3,3) se quiere mover hacia arriba, entonces en vez de sumarle 1 a su coordenada Y debería restársela. Cabe aclarar, que las coordenadas fueron extraídas directamente desde el output entregado por el programa.

![Sin título](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/105676376/a9bab86d-73ed-43ed-8ba3-559643e3c22c)

Otro ejemplo:

![image](https://github.com/IIC2613-Inteligencia-Artificial-2023-2/Syllabus/assets/105676376/bdbed16b-6db8-475c-90f9-dbdf963fbae1)

**Comment by Jairuru** [comment]
Quiero agregar a la duda si pueden aclarar el tema de la dirección donde está mirando el robot. Si la posición Y + 1 está hacia abajo en la grilla con respecto a Y, entonces mirar hacia arriba sería el icono del robot mirando hacia abajo (afuera de la pantalla)? O mirar hacia arriba sería mirar hacia la posición Y - 1?

**Comment by dfloreaa** [comment]
Hola, tienes toda la razón, esto será corregido en el código base en la proximidad, en todo caso, consideraremos esto a la hora de corregir las entregas. En principio el robot debería mirar hacia abajo cuando se mueve hacia abajo, por lo que vamos a corregir el visualizador para que refleje esto.

Un saludo,
Daniel

**Comment by benja20029** [comment]
> Hola, tienes toda la razón, esto será corregido en el código base en la proximidad, en todo caso, consideraremos esto a la hora de corregir las entregas. En principio el robot debería mirar hacia abajo cuando se mueve hacia abajo, por lo que vamos a corregir el visualizador para que refleje esto.
> 
> Un saludo, Daniel

En mi caso, debido a este error, no me estaba pasando los tests, asi que los di vuelta y los logre pasar. Debido a lo anterior, creo que no volveria a pasar los tests si vuelven a dar vuelta los ssettings para que porfa tengan en consideracion eso al momento de revisar ;(

**Comment by dfloreaa** [comment]
@benja20029 se hizo un anuncio con el cambio el día 29 de agosto. Anuncios en la página del curso se dan como conocidos para propósitos de corrección.

Ahora bien, claramente no te quiero perjudicar, te voy a dar un día extra para arreglar este problema en tu entrega **(y solo ese problema)**, en principio solo debería ser llevar a cabo el cambio que fue comentado en el anuncio.

Debes cambiar las líneas 13 y 14 del código base por:
`robotOn(R, X, Y - 1, T + 1) :- exec(R, up, T), robotOn(R, X, Y, T), time(T + 1).`
`robotOn(R, X, Y + 1, T + 1) :- exec(R, down, T), robotOn(R, X, Y, T), time(T + 1).`

En caso de tener cualquier duda al respecto mándame un correo a iic2613@ing.puc.cl. Saludos.
