### ISSUE TITLE
[T5] Duda sobre formato de respuestas teóricas

### ISSUE THREAD

**Issue by dedmu5** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#70]
Hola, veo que en el notebook de DCCasas están escritas las preguntas teóricas. Sin embargo, me gustaría responder estas en el mismo archivo pdf que DCCanario ya que como debo citar me es más cómodo usar latex. Es posible esto?

Saludos

**Comment by dfloreaa** [comment]
Claro, no hay problema

Saludos ✨
