### ISSUE TITLE
[T5] DCCanario Duda archivo q_table.csv

### ISSUE THREAD

**Issue by M4rtinL4gies** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#71]
Hola! 
¿La Q-Table del agente que debemos guardar en el archivo q_table.csv debe ser la de algún modelo en específico (usando los hiper-parámetros que vienen en el código base) o podemos determinar nosotros qué modelo guardar?

**Comment by dfloreaa** [comment]
Ustedes determinan qué modelo guardar, la idea es que jueguen con los hiperparámetros para generar el mejor agente posible. El _csv_ solo guardará su Q-Table.

Saludos ✨
