### ISSUE TITLE
Archivo entrega T2

### ISSUE THREAD

**Issue by jicartagena** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#8]
Hola! Queria preguntar sobre que se entrega exactamente en la tarea, específicamente en la parte de código. Se que es un archivo clingo pero revisando, no se si se debe (o puede) modificar el propio archivo robots.lp para que cumpla lo pedido, o se debe crear un archivo con código de 0 que permita trabajar esto.

**Comment by dfloreaa** [comment]
Hola, en DCCarrybots el enunciado especifica _"extender el código"_, por lo que debes trabajar sobre el mismo archivo `robots.lp`.

En el caso de DCCudoku recomiendo trabajar con un archivo llamado `solucion.lp` o similar, la corrección revisará la presencia de algún archivo `.lp` en la carpeta y lo ejecutará para cada test.

Éxito con tu tarea 😊✨

**Comment by annaramon** [comment]
Mi codigo robots.lp debería solucionar todos los tests? Es que después de añadir la energía, tengo 6 parámetros y los tests de direccionalidad son con 5 parámetros.

**Comment by dfloreaa** [comment]
Hola, no. Solamente los test con energía implementada (`testE_.lp`)
