### ISSUE TITLE
plano cartesiano DCCudoku

### ISSUE THREAD

**Issue by a-ck** [IIC2613-Inteligencia-Artificial-2023-2/Syllabus#9]
Hola! No me queda claro cómo son los ejes x e y de esta parte, ya que noto inconsistencias entre el enunciado y entre los mismos tests. Por ejemplo en el test 2 se definen las figuras 3 y 4 son "horizontales" pero una va aumentando en el eje x y la otra en el y:

% Figura 2
% 2
% 4
bloque(5,2,0,0,2).
bloque(6,2,1,0,4).

% Figura 3
% 2 3 4
bloque(7,3,**0,0**,2).
bloque(8,3,**1,0**,3).
bloque(9,3,**2,0**,4).

% Figura 4
% 5 1
bloque(10,4,**0,0**,5).
bloque(11,4,**0,1**,1).

No sé si me explico...

**Comment by dfloreaa** [comment]
Hola, me contacté con los ayudantes a cargo y efectivamente la figura 3 en los test 1 y 2 se encuentra con el eje de coordenadas invertido, esto será corregido a la brevedad y actualizado en el repositorio base de la tarea.

Un saludo y gracias por notarlo 😊✨,
Daniel

**Comment by a-ck** [comment]
buena gracias! entonces solo para confirmar, tomamos el plano cartesiano exactamente igual al de la parte de los robots verdad?

**Comment by dfloreaa** [comment]
Sí, como si de una matriz se tratase.

Los cambios realizados son:

- **test1.lp:**
Cambiar línea 28 por: bloque(9,3,1,0,2).

- **test2.lp:**
Cambiar línea 26 por: bloque(8,3,0,1,3).
Cambiar línea 27 por: bloque(9,3,0,2,4).
Cambiar línea 65 por: bloque(25,9,1,0,1).

Gracias por comentar el error! 🐛✨

**Comment by dfloreaa** [comment]
_(Solo para clarificar en caso de que alguien no haya entendido, el eje X va de arriba hacia abajo y el eje Y va de izquierda a derecha)_

**Comment by annaramon** [comment]
No me queda claro... Si visualizas los robots en su posición inicial (X,Y) , por ejemplo (3,2) se entiende como 3 a la derecha y 2 hacia bajo. De modo que yo entiendo que en los robots, el eje X va de izquierda a derecha y el Y de arriba a bajo.

En el caso del sudoku parece que los ejes estén al revés, como comentas: el eje X va de arriba hacia abajo y el eje Y va de izquierda a derecha.

Entonces, ¿cómo se debe contemplar?

Gracias!

**Comment by dfloreaa** [comment]
@annaramon Si, hubo una descoordinación entre quienes desarrollaron cada parte de la tarea y en _DCCarrybots_ el eje X apunta de izquierda a derecha, mientras que el Y apunta de arriba hacia abajo. Para _DCCudoku_ es como comenté anteriormente.

Lamento fuertemente la confusión que esto puede generar, haremos lo mejor para evitarlo en entregas futuras. 😊

**Comment by benja20029** [comment]
> Sí, como si de una matriz se tratase.
> 
> Los cambios realizados son:
> 
> * **test1.lp:**
>   Cambiar línea 28 por: bloque(9,3,1,0,2).
> * **test2.lp:**
>   Cambiar línea 26 por: bloque(8,3,0,1,3).
>   Cambiar línea 27 por: bloque(9,3,0,2,4).
>   Cambiar línea 65 por: bloque(25,9,1,0,1).
> 
> Gracias por comentar el error! 🐛✨

En este ejemplo la linea 65 es la misma que esta en el test actualmente. Asumo que no hay cambio o fue una equivocacion??

**Comment by dfloreaa** [comment]
@benja20029 la definición era correcta desde un inicio, fue un error mío aparentemente el pensar que no (son lo mismo)
